"""Emit the main paper table (screenshot style: one row per method, metric
columns with up/down arrows, bold best, underline second-best) from the
aggregated PartiPrompts overall summary.

Reads:  outputs_parti/parti_summary_overall.csv  (band == 'ALL' rows)
Writes: outputs_parti/parti_table_main.tex

Covers the three arms a single run tree produces. For the full eight-row
paper table (both JIVE operators, standalone CADS, and both +CADS
combinations, each from its own run tree) use jive_bands_table.py.

Run after aggregate_parti.py:  python analysis/make_main_table.py
"""
import csv
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "outputs_parti", "parti_summary_overall.csv")
OUT = os.path.join(ROOT, "outputs_parti", "parti_table_main.tex")

COLUMNS = [
    ("CLIP-IQA", "clip_iqa", True, ".3f"),
    ("HPSv2", "hpsv2", True, ".4f"),
    ("CLIP", "clip_score", True, ".2f"),
    ("KID", "kid_vs_deterministic_mean", False, ".3f"),
    ("Feat.\\ Vendi", "vendi_dino_q1", True, ".3f"),
    ("Pixel Vendi", "pixel_vendi", True, ".3f"),
    ("Pair.\\ $L_2$", "mean_pairwise_l2", True, ".1f"),
]

ARMS = [("deterministic", "Unmodified sampler"), ("oscar", "OSCAR"), ("jive", "JIVE")]


def main():
    with open(SRC) as f:
        rows = {r["arm"]: r for r in csv.DictReader(f) if r["band"] == "ALL"}
    missing = [a for a, _ in ARMS if a not in rows]
    if missing:
        raise SystemExit(f"arms missing from {SRC}: {missing}")

    table = {a: [float(rows[a][stem + "_mean"]) for _, stem, _, _ in COLUMNS] for a, _ in ARMS}

    styles = {}
    for j, (_, _, hib, _) in enumerate(COLUMNS):
        order = sorted(range(len(ARMS)), key=lambda i: table[ARMS[i][0]][j], reverse=hib)
        styles[(ARMS[order[0]][0], j)] = "textbf"
        styles[(ARMS[order[1]][0], j)] = "underline"

    def cell(arm, j, fmt):
        v = format(table[arm][j], fmt)
        if table[arm][j] < 0:
            v = "$-$" + v.lstrip("-")
        st = styles.get((arm, j))
        return f"\\{st}{{{v}}}" if st else v

    lines = [
        "% Auto-generated by make_main_table.py from outputs_parti/parti_summary_overall.csv",
        "% Requires: \\usepackage{booktabs}",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{PartiPrompts (1{,}632 prompts, FLUX.1-schnell, 16 images per arm, "
        "identical starting latents). KID is measured against the deterministic arm. "
        "\\textbf{Bold}: best; \\underline{underline}: second best.}",
        "\\label{tab:parti-main}",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\small",
        "\\begin{tabular}{l" + "c" * len(COLUMNS) + "}",
        "\\toprule",
        "Method & " + " & ".join(
            f"{h}$\\{'uparrow' if hib else 'downarrow'}$" for h, _, hib, _ in COLUMNS) + " \\\\",
        "\\midrule",
    ]
    for arm, label in ARMS:
        cells = " & ".join(cell(arm, j, COLUMNS[j][3]) for j in range(len(COLUMNS)))
        lines.append(f"{label} & {cells} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("wrote", OUT)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
